application: youtube-dl

version: alpha-3-5
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /api/.*
  script: mainGAE.py
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.1"
- name: ssl
  version: latest


skip_files:
# Default values from https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Skipping_files
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# Custom values
- ^VENV.*$
- ^.*\.egg.*$
- ^gae/tmp/.*$
- ^dist/.*$
- ^docs/.*$
- ^test/.*$
- ^devscripts/.*$
