application: youtube-dl

version: alpha
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /api/.*
  script: mainGAE.py

- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.1"
